server:
  port: 8090

spring:
  application:
    name: market-search-service
  config:
    import: "optional:configserver:http://localhost:8888"
finnhub:
  api:
    key: d4se4apr01qvsjbh6j00d4se4apr01qvsjbh6j0g
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/marketsearchdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
resilience4j:
  circuitbreaker:
    instances:
      finnhubSearch:
        registerHealthIndicator: true
        slidingWindowSize: 10          # number of calls to measure
        minimumNumberOfCalls: 5        # before calculating failure rate
        failureRateThreshold: 50       # % of failures to trip breaker
        waitDurationInOpenState: 30s   # how long breaker stays open
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      finnhubSearch:
        maxAttempts: 3                 # total attempts
        waitDuration: 2s               # delay between retries
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException

  timelimiter:
    instances:
      finnhubSearch:
        timeoutDuration: 3s            # max time per call
        cancelRunningFuture: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 5MB



quotes-service:
  url: http://localhost:8091


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: market-search
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
alphavantage:
  apikey: VBMC8IRO31QQLMZD

