global:
  scrape_interval: 55s
  evaluation_interval: 55s

scrape_configs:

  - job_name: "api-gateway"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8081"]
        labels:
          application: "api-gateway"

  - job_name: "discovery-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8761"]
        labels:
          application: "discovery-service"

  - job_name: "user-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8096"]
        labels:
          application: "user-service"

  - job_name: "quotes-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8091"]
        labels:
          application: "quotes-service"

  - job_name: "historical-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8094"]
        labels:
          application: "historical-service"

  - job_name: "market-search-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8090"]
        labels:
          application: "market-search-service"

  - job_name: "watchlist-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8076"]
        labels:
          application: "watchlist-service"
